name: Build Modified Firmware 
on: [workflow_dispatch] 

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Repo 
        uses: actions/checkout@v4 

      - name: Setup Tools 
        run: | 
          sudo apt-get update 
          sudo apt-get install -y lz4 android-sdk-libsparse-utils 

      - name: Download Firmware 
        run: | 
          aria2c -x8 "https://samfw.com/firmware/SM-A326U1/XAA/A326U1UESBDWI1" -d firmware/original/ 